# Render Blueprint for EcoTrack Ghana API
services:
  - type: web
    name: ecotrack-ghana-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.production.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: ALLOWED_IMAGE_TYPES
        value: image/jpeg,image/png,image/webp
      - key: DATABASE_URL
        fromDatabase:
          name: ecotrack-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,https://www.your-frontend-domain.com

databases:
  - name: ecotrack-db
    plan: starter
    databaseName: ecotrack_ghana
    user: ecotrack_user
